# Generated by Django 3.0.4 on 2020-03-06 06:00
import itertools
import random

from django.db import migrations

from core.factories import UserFactory, EventFactory

USER_COUNT = 100
EVENT_COUNT = 1000
BULK_COUNT = 10000
USERS_EVENTS_COUNT = USER_COUNT * EVENT_COUNT


def create_initial_users():
    UserFactory.create_batch(USER_COUNT)


def create_initial_events():
    EventFactory.create_batch(EVENT_COUNT)


def set_default_worker_settings(apps, schema_editor):
    WorkerSettings = apps.get_model('core', 'WorkerSettings')
    WorkerSettings.objects.create(step=10000, last_checked_id=0)


def create_users_events_data(apps, schema_editor):
    RawData = apps.get_model('core', 'RawData')
    User = apps.get_model('core', 'User')
    Event = apps.get_model('core', 'Event')
    create_initial_users()
    create_initial_events()
    user_qs = User.objects.filter(pk__range=(0, USER_COUNT))
    event_qs = Event.objects.filter(pk__range=(0, EVENT_COUNT))
    users_events = itertools.product(user_qs, event_qs)
    for i in range(0, USERS_EVENTS_COUNT, BULK_COUNT):
        rows = []
        for j in range(BULK_COUNT):
            user, event = next(users_events)
            rows.append(RawData(user=user, event=event, amount=random.randint(-100000, 100000)))
        RawData.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_users_events_data, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_default_worker_settings, reverse_code=migrations.RunPython.noop
        ),
    ]
