# Generated by Django 3.0.4 on 2020-03-06 06:00
import itertools
import random

from django.db import migrations

from core.factories import UserFactory, EventFactory

USER_COUNT = 100
EVENT_COUNT = 1000
BULK_COUNT = 10000
USERS_EVENTS_COUNT = USER_COUNT * EVENT_COUNT


def create_initial_users():
    return UserFactory.create_batch(USER_COUNT)


def create_initial_events():
    return EventFactory.create_batch(EVENT_COUNT)


def create_users_events_data(apps, schema_editor):
    RawData = apps.get_model('core', 'RawData')
    users = create_initial_users()
    events = create_initial_events()
    users_events = itertools.product(users, events)
    for i in range(0, USERS_EVENTS_COUNT, BULK_COUNT):
        rows = []
        for j in range(BULK_COUNT):
            user, event = next(users_events)
            rows.append(RawData(user=user, event=event, amount=random.randint(-100000, 100000)))
        RawData.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_users_events_data, reverse_code=migrations.RunPython.noop
        ),
    ]
